source 'https://rubygems.org'

gem 'rake'
gem 'faraday'
gem 'net-http-persistent'
gem 'progress'
gem 'haml'
gem 'middleman'
gem 'middleman-livereload'
gem 'middleman-sprockets', '>= 4.0.0.rc'
gem 'bootstrap-sass'
gem 'font-awesome-sass', '~> 4.5.0'
