source 'https://rubygems.org'

gem 'bootstrap-sass'
gem 'faraday'
gem 'font-awesome-sass'
gem 'haml'
gem 'middleman'
gem 'middleman-livereload'
gem 'middleman-sprockets'
gem 'net-http-persistent'
gem 'progress'
gem 'rake'
